base_url = "https://killeik.net"
title = "killeik grimoire"
description = "personal magical book on the web"
default_language = "en"
compile_sass = true
build_search_index = false
minify_html = true
generate_feeds = true
feed_filenames = ["feed.xml"]

taxonomies = [
  { name = "tags", feed = true },
]

[slugify]
paths = "off"

[markdown]
smart_punctuation = false

[extra]
author = "killeik"
email = "sixwingedkilleik@gmail.com"
