# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: killeik/online
  branch: eleventy
  squash_merges: true
  site_domain: d09d1d54-27d1-4d2b-b7c4-67dc5509d2ab

publish_mode: editorial_workflow
media_folder: "source/_static/uploads"
public_folder: "/uploads"

site_url: "https://killeik.net"
display_url: "https://killeik.net"
logo:
  src: "/favicon.png"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "thoughts"
    label: "Whispers"
    label_singular: "Whisper"
    folder: "source/thoughts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Created", name: "created", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { name: "date", widget: "hidden", default: "git Last Modified" }
      - { name: "layout", widget: "hidden", default: "base.liquid" }
      - { name: "tags", widget: "hidden", default: ["thought"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "richtext" }

  - name: "marginalia"
    label: "Marginalia"
    label_singular: "Marginalium"
    folder: "source/marginalia/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    editor:
      preview: false
    fields:
      - { label: "Created", name: "created", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "title", widget: "hidden", default: "{{datetime}}" }
      - { name: "date", widget: "hidden", default: "git Last Modified" }
      - { name: "layout", widget: "hidden", default: "marginalia-post.liquid" }
      - { name: "tags", widget: "hidden", default: ["marginalia"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "richtext" }

  - name: "websites"
    label: "Websites"
    label_singular: "Website"
    folder: "source/web/websites"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Created", name: "created", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { name: "date", widget: "hidden", default: "git Last Modified" }
      - { name: "layout", widget: "hidden", default: "websitecard.liquid" }
      - { label: "Tags", name: "tags", widget: "list", default: ["webindex"] }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Description", name: "body", widget: "richtext", required: false }

  - name: "pages"
    label: "Main pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "source/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Created", name: "created", widget: "string", required: false }
          - { label: "Updated", name: "date", widget: "string", required: false }
          - { name: "layout", widget: "hidden", default: "title.liquid" }
          - { label: "Body", name: "body", widget: "richtext" }
      - label: "About"
        name: "about"
        file: "source/thoughts/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Created", name: "created", widget: "string", required: false }
          - { label: "Updated", name: "date", widget: "string", required: false }
          - { name: "layout", widget: "hidden", default: "base.liquid" }
          - { label: "Body", name: "body", widget: "richtext" }
      - label: "Tinkering"
        name: "tinkering"
        file: "source/tinkering.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Created", name: "created", widget: "string", required: false }
          - { label: "Updated", name: "date", widget: "string", required: false }
          - { name: "layout", widget: "hidden", default: "base.liquid" }
          - { label: "Body", name: "body", widget: "richtext" }
      - label: "Contact"
        name: "contact"
        file: "source/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Created", name: "created", widget: "string", required: false }
          - { label: "Updated", name: "date", widget: "string", required: false }
          - { name: "layout", widget: "hidden", default: "base.liquid" }
          - { label: "Body", name: "body", widget: "richtext" }
